language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: JLap9IE7e/HSADojwnYE3A794zJS0743oH5A//esXQ2o7paKTLoB4b55Kx72hWgrk/xyMNIvEiulM0xjACaJZuF1L30V0C8Y2GoVlhoY8RNEzQ3/bTrCHlmgmT8t2Rg6x6mdXnVsmUn8br4GxpZadWjDwOggzEVrc+3QDsml0N87Xl4Iib89NULoINYfyEuAu3MTeYCLjW5ElE2rDpYOWNFegSFMA52+1PR4KhixVZ80XS9kjRZWSGq3PPqWy1/By0pqRb8yGJ8GIDDAkcQeJRjeNzHF/Aycn8OA84NNpr5hD5QbqYeX0XgISTv7mdxgJf71DmFmSSm8qvVwmdCZ/9uB+B6LUgBDlHIZy2GEmsc2NWgu0OV85AAAICmRelGst6uJx5cHFvvbge6xPahm2WrrkUz7Bh+eGZL30/wB29R+Am3hopJHJtseTqYVX1lZ0gDbZ41uzle7UVI+FMNO0n42P66UMi/IE1SWAWlByBXesEuCApAwRMz4uBa+sq2BXLl0C9RWLfYXuVI6tK6JcfocgN2jKGmlEIaO6FCcTwOl+s0nTrmwOyOqVOfIjSub+9D79AKQPAjzFLgj9AljyTgE27mn0vGnVZMqwpqh/CNBvhLEe/SshtlexBWJKSyLSDt1ncAEk3pbT83JLo0xgiYNyZTNSPDmBukIXzRCe7s=
  app: tranquil-depths-85161

  on:
    repo: lakerfan1994/react-hot-cold
